# Generated by Django 5.0.4 on 2024-04-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rentdata_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdata',
            name='paid_true',
            field=models.BooleanField(default=True),
        ),
    ]
