# Generated by Django 5.0.4 on 2024-04-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclesForRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_image', models.ImageField(null=True, upload_to='vehicles_images')),
                ('mark', models.CharField(blank=True, max_length=65, unique=True)),
                ('model', models.CharField(blank=True, max_length=65, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('about_vehicle', models.TextField(blank=True)),
                ('price', models.FloatField(null=True)),
                ('available', models.BooleanField(default=False)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
