# Generated by Django 5.0.4 on 2024-04-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehiclesforrent_color_vehiclesforrent_engine_val_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesforrent',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles_logo'),
        ),
        migrations.AlterField(
            model_name='vehiclesforrent',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles_images'),
        ),
    ]
