# Generated by Django 5.0.4 on 2024-04-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehiclesforrent_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesforrent',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='vehiclesforrent',
            name='gear_box',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
