# Generated by Django 5.0.4 on 2024-04-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehiclesforrent_fuel_type_vehiclesforrent_gear_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesforrent',
            name='discount',
            field=models.BooleanField(default=False),
        ),
    ]
